from pathlib import Path

from jinja2 import Environment, PackageLoader, select_autoescape  # type:ignore
from typing import List

from storylc.model import Movie, Scene
from storylc.project_logs import a_logger

here = Path(__file__).absolute().parent

def get_old(outfile: Path) -> str: ...
def generate_omakeroot(movie: Movie, out: Path) -> bool: ...
def generate_omakefile(movie: Movie, out: Path) -> bool: ...
def generate(movie: Movie, out: Path): ...
def copy_src(movie: Movie, out: Path): ...
def copy_mp(out: Path): ...
def generate_omakefile_scene(scene: Scene, out: Path) -> bool: ...
def generate_master_tex(movie: Movie, out: Path) -> bool: ...
def generate_omakefile_mps(movie: Movie, out: Path) -> bool: ...
def make_starts(movie: Movie) -> List[int]: ...
def generate_timeline(movie: Movie, out: Path) -> bool: ...
def generate_scene(movie: Movie, scene: Scene, out: Path): ...
