from pathlib import Path

from jinja2 import Environment, PackageLoader, select_autoescape  # type:ignore
from storylc.model import Movie, Scene
from storylc.project_logs import a_logger

here = Path(__file__).absolute().parent

def get_old(outfile: Path) -> str: ...
def generate_omakeroot(movie: Movie, out: Path) -> bool: ...
def generate_omakefile(movie: Movie, out: Path) -> bool: ...
def generate(movie: Movie, out: Path): ...
