from typing import List, Optional

from storylc.model import Animation, Layer, Movie

def get_animation(movie: Movie, name: str) -> Animation: ...
def animation_of_layer(movie: Movie, layer: Layer) -> Animation: ...
